/**
 * 业务错误码常量
 */
export const ERROR_CODES = {
  // 用户相关
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERNAME_EXISTS: 'USERNAME_EXISTS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  EMAIL_IN_USE: 'EMAIL_IN_USE',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  CANNOT_DELETE_LAST_ADMIN: 'CANNOT_DELETE_LAST_ADMIN',

  // 认证相关
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_BLACKLISTED: 'TOKEN_BLACKLISTED',

  // 权限相关
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  INSUFFICIENT_PRIVILEGES: 'INSUFFICIENT_PRIVILEGES',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',

  // 业务逻辑相关
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  INVALID_OPERATION: 'INVALID_OPERATION',

  // 路由相关
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',

  // 资源相关
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',

  // 组件管理相关
  COMPONENT_NOT_FOUND: 'COMPONENT_NOT_FOUND',
  COMPONENT_ALREADY_EXISTS: 'COMPONENT_ALREADY_EXISTS',
  COMPONENT_ID_INVALID: 'COMPONENT_ID_INVALID',
  COMPONENT_VERSION_NOT_FOUND: 'COMPONENT_VERSION_NOT_FOUND',
  COMPONENT_VERSION_ALREADY_EXISTS: 'COMPONENT_VERSION_ALREADY_EXISTS',
  COMPONENT_VERSION_INVALID: 'COMPONENT_VERSION_INVALID',
  COMPONENT_HAS_PUBLISHED_VERSIONS: 'COMPONENT_HAS_PUBLISHED_VERSIONS',
  COMPONENT_UPDATE_FAILED: 'COMPONENT_UPDATE_FAILED',

  // 组件分类相关
  COMPONENT_CATEGORY_NOT_FOUND: 'COMPONENT_CATEGORY_NOT_FOUND',
  COMPONENT_CATEGORY_ALREADY_EXISTS: 'COMPONENT_CATEGORY_ALREADY_EXISTS',
  COMPONENT_CATEGORY_CODE_EXISTS: 'COMPONENT_CATEGORY_CODE_EXISTS',
  COMPONENT_CATEGORY_PARENT_REQUIRED: 'COMPONENT_CATEGORY_PARENT_REQUIRED',
  COMPONENT_CATEGORY_INVALID_PARENT: 'COMPONENT_CATEGORY_INVALID_PARENT',
  COMPONENT_CATEGORY_HAS_CHILDREN: 'COMPONENT_CATEGORY_HAS_CHILDREN',
  COMPONENT_CATEGORY_HAS_COMPONENTS: 'COMPONENT_CATEGORY_HAS_COMPONENTS',
  INVALID_CLASSIFICATION: 'INVALID_CLASSIFICATION',

  // 组件版本相关
  COMPONENT_VERSION_ALREADY_PUBLISHED: 'COMPONENT_VERSION_ALREADY_PUBLISHED',
  COMPONENT_VERSION_ALREADY_DRAFT: 'COMPONENT_VERSION_ALREADY_DRAFT',
  COMPONENT_VERSION_NOT_PUBLISHED: 'COMPONENT_VERSION_NOT_PUBLISHED',
  COMPONENT_VERSION_COMPONENT_MISMATCH: 'COMPONENT_VERSION_COMPONENT_MISMATCH',
  COMPONENT_VERSION_IS_LATEST: 'COMPONENT_VERSION_IS_LATEST',
  COMPONENT_VERSION_PUBLISH_FAILED: 'COMPONENT_VERSION_PUBLISH_FAILED',
  COMPONENT_VERSION_UNPUBLISH_FAILED: 'COMPONENT_VERSION_UNPUBLISH_FAILED',
  COMPONENT_VERSION_UPDATE_FAILED: 'COMPONENT_VERSION_UPDATE_FAILED',
  COMPONENT_VERSION_DELETE_FAILED: 'COMPONENT_VERSION_DELETE_FAILED',

  // 组件上传相关
  INVALID_ZIP_FILE: 'INVALID_ZIP_FILE',
  ZIP_FILE_TOO_LARGE: 'ZIP_FILE_TOO_LARGE',
  META_JSON_NOT_FOUND: 'META_JSON_NOT_FOUND',
  META_JSON_INVALID: 'META_JSON_INVALID',
  ENTRY_FILE_NOT_FOUND: 'ENTRY_FILE_NOT_FOUND',
  MISSING_REQUIRED_FILES: 'MISSING_REQUIRED_FILES',
  MISSING_DECLARED_FILES: 'MISSING_DECLARED_FILES',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',

  // OSS相关
  OSS_UPLOAD_FAILED: 'OSS_UPLOAD_FAILED',
  OSS_DELETE_FAILED: 'OSS_DELETE_FAILED',
  OSS_FILE_NOT_FOUND: 'OSS_FILE_NOT_FOUND'
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
