/**
 * 业务错误码常量
 */
export const ERROR_CODES = {
  // 用户相关
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERNAME_EXISTS: 'USERNAME_EXISTS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  EMAIL_IN_USE: 'EMAIL_IN_USE',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  CANNOT_DELETE_LAST_ADMIN: 'CANNOT_DELETE_LAST_ADMIN',

  // 认证相关
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_BLACKLISTED: 'TOKEN_BLACKLISTED',

  // 权限相关
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  INSUFFICIENT_PRIVILEGES: 'INSUFFICIENT_PRIVILEGES',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',

  // 业务逻辑相关
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  INVALID_OPERATION: 'INVALID_OPERATION',

  // 路由相关
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND'
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
